CREATE TABLE BRANCH (B_ID INT NOT NULL PRIMARY KEY, B_Mng_ID INT NOT NULL, B_Location VARCHAR(255)); 

CREATE TABLE CLASS(C_Section INT NOT NULL PRIMARY KEY, C_Name VARCHAR(255) NOT NULL, C_Branch_ID INT NOT NULL, C_Capacity INT );

CREATE TABLE EQUIPMENT (Eq_ID INT NOT NULL PRIMARY KEY, Eq_Branch_ID INT NOT NULL , Eq_In_Use NUMBER(1) NOT NULL, Eq_Condition VARCHAR(255), Eq_Name VARCHAR(255));

CREATE TABLE FEE (F_ID INT NOT NULL PRIMARY KEY, F_Paid NUMBER(1) NOT NULL, F_Amnt_Due DECIMAL, F_Date_Due DATE, F_Pay_Method INT);

CREATE TABLE MEMBER (M_Username VARCHAR(50) PRIMARY KEY, M_Gender VARCHAR(6), M_Birthday DATE, M_FName VARCHAR(20) NOT NULL, M_LName VARCHAR(20) NOT NULL, M_Password VARCHAR(20) NOT NULL, M_Branch_ID INT NOT NULL, M_Emg_Contact INT, M_Phone INT);

CREATE TABLE MEMBERSHIP (MS_ID INT NOT NULL PRIMARY KEY, MS_Type VARCHAR(255), MS_Expiry_Date DATE, MS_Start_Date DATE, MS_Consecutive INT, MS_Cost INT, MS_Username VARCHAR(100));

CREATE TABLE SCHEDULE (Sched_ID INT NOT NULL PRIMARY KEY, Sched_Start_Time TIMESTAMP WITH TIME ZONE, Sched_End_Time TIMESTAMP WITH TIME ZONE);

CREATE TABLE SELLABLE (SELL_ID INT NOT NULL PRIMARY KEY, SELL_Qnt_Storage INT, SELL_Qnt_Available INT NOT NULL, SELL_Price FLOAT NOT NULL);

CREATE TABLE SHOP (SHOP_ID INT NOT NULL PRIMARY KEY, SHOP_BestSeller_ID INT NOT NULL );

CREATE TABLE AVAILABLE_IN (A_SHOP_ID INT NOT NULL, A_SELL_ID INT NOT NULL, PRIMARY KEY (A_SHOP_ID, A_SELL_ID), FOREIGN KEY (A_SHOP_ID) REFERENCES SHOP (SHOP_ID), FOREIGN KEY (A_SELL_ID) REFERENCES SELLABLE (SELL_ID));

CREATE TABLE BODY_COMPOSITION (BC_Date DATE NOT NULL, Weight INT, BC_Height INT, BC_PBodyFat INT, BC_PMuscleMass INT, BC_M_ID VARCHAR(20) NOT NULL, PRIMARY KEY (BC_Date, BC_M_ID), FOREIGN KEY (BC_M_ID) REFERENCES MEMBER (M_Username));

CREATE TABLE BRANCH_PHONE (BP_BRANCH_ID INT NOT NULL, BP_Phone CHAR(8) NOT NULL, FOREIGN KEY (BP_BRANCH_ID) REFERENCES BRANCH (B_ID));

CREATE TABLE EMPLOYEE(E_ID int NOT NULL PRIMARY KEY, E_Gender VARCHAR(255) , E_Age INT, E_Salary DECIMAL , E_FName VARCHAR(255) NOT NULL, E_LName varchar(255) NOT NULL, E_Address varchar(255), E_Shop_ID INT NOT NULL, E_Keeping_Days VARCHAR(250), E_BRANCH_ID INT NOT NULL, E_Super_ID INT, E_CLASS_ID INT NOT NULL, FOREIGN KEY (E_CLASS_ID) REFERENCES CLASS (C_Section), FOREIGN KEY (E_BRANCH_ID) REFERENCES BRANCH (B_ID), FOREIGN KEY (E_Super_ID) REFERENCES EMPLOYEE (E_ID) );

CREATE TABLE EMPLOYEE_PHONE (EP_EMPLOYEE_ID INT NOT NULL, EP_PHONE CHAR(8) NOT NULL, PRIMARY KEY (EP_EMPLOYEE_ID, EP_PHONE), FOREIGN KEY (EP_EMPLOYEE_ID) REFERENCES EMPLOYEE (E_ID));

CREATE TABLE EMPLOYEE_SHIFT (ES_EMPLOYEE_ID INT NOT NULL, ES_SHIFT VARCHAR(5) NOT NULL, PRIMARY KEY (ES_EMPLOYEE_ID, ES_SHIFT), FOREIGN KEY (ES_EMPLOYEE_ID) REFERENCES EMPLOYEE(E_ID));

CREATE TABLE FOLLOWS (FOL_CLASS_ID NOT NULL PRIMARY KEY, FOL_SCHED_ID INT NOT NULL, FOREIGN KEY (FOL_SCHED_ID) REFERENCES SCHEDULE (Sched_ID), FOREIGN KEY (FOL_CLASS_ID) REFERENCES CLASS (C_Section));

CREATE TABLE PAYS (P_MEMBER_ID VARCHAR(15) NOT NULL, P_FEE_ID INT NOT NULL, PRIMARY KEY (P_MEMBER_ID, P_FEE_ID), FOREIGN KEY (P_MEMBER_ID) REFERENCES MEMBER (M_Username), FOREIGN KEY (P_FEE_ID) REFERENCES FEE (F_ID));

CREATE TABLE TAKES_PLACE_IN (TPI_BRANCH_ID INT NOT NULL, TPI_SHOP_ID INT NOT NULL, PRIMARY KEY (TPI_BRANCH_ID, TPI_SHOP_ID), FOREIGN KEY (TPI_BRANCH_ID) REFERENCES BRANCH (B_ID), FOREIGN KEY (TPI_SHOP_ID) REFERENCES SHOP (SHOP_ID));

CREATE TABLE USES (U_MEMBER_ID VARCHAR(15) NOT NULL, U_EQUIPMENT_ID INT NOT NULL, PRIMARY KEY (U_MEMBER_ID, U_EQUIPMENT_ID),  FOREIGN KEY (U_MEMBER_ID) REFERENCES MEMBER (M_Username),  FOREIGN KEY (U_EQUIPMENT_ID) REFERENCES EQUIPMENT (Eq_ID) );